[tool.ruff]
line-length = 120
select = ["E", "F", "I"]

[tool.black]
line-length = 120

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
disallow_untyped_defs = true
warn_return_any = true

[[tool.mypy.overrides]]
module = [
    'sklearn.*',
    'fire',
    'torchvision',
    'torchvision.*',
    'clip',
    'clip.*',
    'essential_generators',
    'transformers',
    'scipy',
    'scipy.*',
]
ignore_missing_imports = true
